FROM openjdk:17-jdk-slim

RUN apt-get update && apt-get install -y python3 python3-pip

RUN pip3 install pdfplumber

WORKDIR /app

COPY build/libs/highfourm-0.0.1-SNAPSHOT.jar ./highfourm.jar
COPY scripts/ ./scripts/

COPY shell.sh ./shell.sh
RUN chmod +x ./shell.sh

ENTRYPOINT [ "sh", "./shell.sh" ]